more changes

diff --git a/.github/workflows/cpp.yml b/.github/workflows/cpp.yml
--- a/.github/workflows/cpp.yml
+++ b/.github/workflows/cpp.yml
@@ -156,44 +156,44 @@ jobs:
         continue-on-error: true
         run: archery docker push ${{ matrix.image }}
 
-  dremio-docker:
-    runs-on: ubuntu-latest
-    outputs:
-      dremio_url: ${{ steps.tunnel.outputs.dremio_url }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: Start and Set Up Dremio
-        run: |
-          cd cpp/src/arrow/flight/sql/odbc/tests/dremio/
-          docker compose up -d
-          sh ./set_up_dremio_instance.sh
-      - name: Install Cloudflared
-        run: |
-          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
-          chmod +x cloudflared
-      - name: Start Tunnel
-        id: tunnel
-        run: |
-          ./cloudflared tunnel --url http://localhost:9047 --no-autoupdate > tunnel.log 2>&1 &
-          sleep 5
-          echo "Tunnel log:"
-          cat tunnel.log
-          TUNNEL_URL=$(grep -oE 'https://[-a-zA-Z0-9]+\.trycloudflare\.com' tunnel.log | head -n 1)
-          echo "dremio_url=$TUNNEL_URL" >> $GITHUB_OUTPUT
-      - name: Verify Cloudflare Tunnel availability
-        run: |
-          echo "Tunnel URL is: ${{ steps.tunnel.outputs.dremio_url }}"
-          for i in {1..10}; do
-            echo "Attempt $i: Checking tunnel availability..."
-            if curl -s -I "${{ steps.tunnel.outputs.dremio_url }}" | grep -q "HTTP"; then
-              echo "Tunnel is responding!"
-              exit 0
-            fi
-            echo "Not ready yet. Retrying in 5 seconds..."
-            sleep 5
-          done
-          echo "🚨 Tunnel failed to become available after 50 seconds."
-          exit 1
+  # dremio-docker:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     dremio_url: ${{ steps.tunnel.outputs.dremio_url }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #     - name: Start and Set Up Dremio
+  #       run: |
+  #         cd cpp/src/arrow/flight/sql/odbc/tests/dremio/
+  #         docker compose up -d
+  #         sh ./set_up_dremio_instance.sh
+  #     - name: Install Cloudflared
+  #       run: |
+  #         curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
+  #         chmod +x cloudflared
+  #     - name: Start Tunnel
+  #       id: tunnel
+  #       run: |
+  #         ./cloudflared tunnel --url http://localhost:9047 --no-autoupdate > tunnel.log 2>&1 &
+  #         sleep 5
+  #         echo "Tunnel log:"
+  #         cat tunnel.log
+  #         TUNNEL_URL=$(grep -oE 'https://[-a-zA-Z0-9]+\.trycloudflare\.com' tunnel.log | head -n 1)
+  #         echo "dremio_url=$TUNNEL_URL" >> $GITHUB_OUTPUT
+  #     - name: Verify Cloudflare Tunnel availability
+  #       run: |
+  #         echo "Tunnel URL is: ${{ steps.tunnel.outputs.dremio_url }}"
+  #         for i in {1..10}; do
+  #           echo "Attempt $i: Checking tunnel availability..."
+  #           if curl -s -I "${{ steps.tunnel.outputs.dremio_url }}" | grep -q "HTTP"; then
+  #             echo "Tunnel is responding!"
+  #             exit 0
+  #           fi
+  #           echo "Not ready yet. Retrying in 5 seconds..."
+  #           sleep 5
+  #         done
+  #         echo "🚨 Tunnel failed to become available after 50 seconds."
+  #         exit 1
 
   build-example:
     name: C++ Minimal Build Example
@@ -330,7 +330,7 @@ jobs:
   windows-mingw:
     name: AMD64 Windows MinGW ${{ matrix.msystem_upper }} C++
     runs-on: windows-2022
-    needs: dremio-docker
+    # needs: dremio-docker
     if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
     # Build may take 1h+ without cache.
     timeout-minutes: 120
@@ -351,6 +351,7 @@ jobs:
       ARROW_FLIGHT: ON
       ARROW_FLIGHT_SQL: ON
       ARROW_FLIGHT_SQL_ODBC: ON
+      ARROW_FLIGHT_SQL_ODBC_CONN: "driver={Apache Arrow Flight SQL ODBC Driver};HOST=localhost;port=32010;uid=admin;pwd=admin2025;useEncryption=false;"
       ARROW_FLIGHT_SQL_ODBC_INSTALLER: ON
       ARROW_GANDIVA: ON
       ARROW_GCS: ON
@@ -402,6 +403,14 @@ jobs:
           path: ccache
           key: cpp-ccache-${{ matrix.msystem_lower}}-${{ hashFiles('cpp/**') }}
           restore-keys: cpp-ccache-${{ matrix.msystem_lower}}-
+      - name: Start Dremio Docker on Windows
+        shell: pwsh
+        run: |
+          docker compose -f cpp/src/arrow/flight/sql/odbc/tests/dremio/docker-compose.yaml up -d
+      - name: Set Up Dremio Docker on Windows
+        shell: pwsh
+        run: |
+          sh cpp/src/arrow/flight/sql/odbc/tests/dremio/set_up_dremio_instance.sh
       # - name: Set ARROW_FLIGHT_SQL_ODBC_CONN
       #   shell: powershell
       #   run: |
@@ -486,14 +495,9 @@ jobs:
       #     sh ./set_up_dremio_instance.sh
       - name: Test
         shell: msys2 {0}
-        env:
-          DREMIO_URL: ${{ needs.dremio-docker.outputs.dremio_url }}
+        # env:
+        #   DREMIO_URL: ${{ needs.dremio-docker.outputs.dremio_url }}
         run: |
-          dremioHost=$(echo $DREMIO_URL | sed -E 's#https?://([^/:]+).*#\1#')
-          echo "Dremio host: $dremioHost"
-          export ARROW_FLIGHT_SQL_ODBC_CONN="driver={Apache Arrow Flight SQL ODBC Driver};HOST=$dremioHost;port=32010;uid=admin;pwd=admin2025;useEncryption=false;"
-          echo "ARROW_FLIGHT_SQL_ODBC_CONN=$ARROW_FLIGHT_SQL_ODBC_CONN"
-
           ci/scripts/cpp_test.sh "$(pwd)" "$(pwd)/build"
       - name: Stop Dremio Docker Container
         run: |
