Add debug logs to see where segfault occurred
Disable other workflows to make it easier.
Add logs

diff --git a/.github/workflows/cpp.yml b/.github/workflows/cpp.yml
--- a/.github/workflows/cpp.yml
+++ b/.github/workflows/cpp.yml
@@ -71,222 +71,222 @@ env:
   DOCKER_VOLUME_PREFIX: ".docker/"
 
 jobs:
-  docker:
-    name: ${{ matrix.title }}
-    runs-on: ${{ matrix.runs-on }}
-    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
-    timeout-minutes: 75
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - arch: amd64
-            clang-tools: 14
-            image: conda-cpp
-            llvm: 14
-            runs-on: ubuntu-latest
-            simd-level: AVX2
-            title: AMD64 Conda C++ AVX2
-            ubuntu: 22.04
-          - arch: amd64
-            clang-tools: 14
-            image: ubuntu-cpp-sanitizer
-            llvm: 14
-            runs-on: ubuntu-latest
-            title: AMD64 Ubuntu 24.04 C++ ASAN UBSAN
-            ubuntu: 24.04
-          - arch: arm64v8
-            clang-tools: 14
-            image: ubuntu-cpp
-            llvm: 14
-            runs-on: ubuntu-24.04-arm
-            title: ARM64 Ubuntu 22.04 C++
-            ubuntu: 22.04
-    env:
-      ARCH: ${{ matrix.arch }}
-      ARROW_SIMD_LEVEL: ${{ matrix.simd-level }}
-      CLANG_TOOLS: ${{ matrix.clang-tools }}
-      LLVM: ${{ matrix.llvm }}
-      UBUNTU: ${{ matrix.ubuntu }}
-    steps:
-      - name: Checkout Arrow
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
-        with:
-          fetch-depth: 0
-          submodules: recursive
-      - name: Cache Docker Volumes
-        uses: actions/cache@v4
-        with:
-          path: .docker
-          key: ${{ matrix.image }}-${{ hashFiles('cpp/**') }}
-          restore-keys: ${{ matrix.image }}-
-      - name: Setup Python on hosted runner
-        if: |
-          matrix.runs-on == 'ubuntu-latest'
-        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
-        with:
-          python-version: 3
-      - name: Setup Python on self-hosted runner
-        if: |
-          contains(matrix.runs-on, 'self-hosted')
-        run: |
-          sudo apt update
-          sudo apt install -y --no-install-recommends python3 python3-dev python3-pip
-          python3 -m pip install -U pip
-      - name: Setup Archery
-        run: python3 -m pip install -e dev/archery[docker]
-      - name: Execute Docker Build
-        env:
-          ARCHERY_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
-          ARCHERY_DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
-        run: |
-          # GH-40558: reduce ASLR to avoid ASAN/LSAN crashes
-          sudo sysctl -w vm.mmap_rnd_bits=28
-          source ci/scripts/util_enable_core_dumps.sh
-          archery docker run ${{ matrix.image }}
-      - name: Docker Push
-        if: >-
-          success() &&
-          github.event_name == 'push' &&
-          github.repository == 'apache/arrow' &&
-          github.ref_name == 'main'
-        env:
-          ARCHERY_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
-          ARCHERY_DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
-        continue-on-error: true
-        run: archery docker push ${{ matrix.image }}
+  # docker:
+  #   name: ${{ matrix.title }}
+  #   runs-on: ${{ matrix.runs-on }}
+  #   if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
+  #   timeout-minutes: 75
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - arch: amd64
+  #           clang-tools: 14
+  #           image: conda-cpp
+  #           llvm: 14
+  #           runs-on: ubuntu-latest
+  #           simd-level: AVX2
+  #           title: AMD64 Conda C++ AVX2
+  #           ubuntu: 22.04
+  #         - arch: amd64
+  #           clang-tools: 14
+  #           image: ubuntu-cpp-sanitizer
+  #           llvm: 14
+  #           runs-on: ubuntu-latest
+  #           title: AMD64 Ubuntu 24.04 C++ ASAN UBSAN
+  #           ubuntu: 24.04
+  #         - arch: arm64v8
+  #           clang-tools: 14
+  #           image: ubuntu-cpp
+  #           llvm: 14
+  #           runs-on: ubuntu-24.04-arm
+  #           title: ARM64 Ubuntu 22.04 C++
+  #           ubuntu: 22.04
+  #   env:
+  #     ARCH: ${{ matrix.arch }}
+  #     ARROW_SIMD_LEVEL: ${{ matrix.simd-level }}
+  #     CLANG_TOOLS: ${{ matrix.clang-tools }}
+  #     LLVM: ${{ matrix.llvm }}
+  #     UBUNTU: ${{ matrix.ubuntu }}
+  #   steps:
+  #     - name: Checkout Arrow
+  #       uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+  #       with:
+  #         fetch-depth: 0
+  #         submodules: recursive
+  #     - name: Cache Docker Volumes
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: .docker
+  #         key: ${{ matrix.image }}-${{ hashFiles('cpp/**') }}
+  #         restore-keys: ${{ matrix.image }}-
+  #     - name: Setup Python on hosted runner
+  #       if: |
+  #         matrix.runs-on == 'ubuntu-latest'
+  #       uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
+  #       with:
+  #         python-version: 3
+  #     - name: Setup Python on self-hosted runner
+  #       if: |
+  #         contains(matrix.runs-on, 'self-hosted')
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install -y --no-install-recommends python3 python3-dev python3-pip
+  #         python3 -m pip install -U pip
+  #     - name: Setup Archery
+  #       run: python3 -m pip install -e dev/archery[docker]
+  #     - name: Execute Docker Build
+  #       env:
+  #         ARCHERY_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
+  #         ARCHERY_DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
+  #       run: |
+  #         # GH-40558: reduce ASLR to avoid ASAN/LSAN crashes
+  #         sudo sysctl -w vm.mmap_rnd_bits=28
+  #         source ci/scripts/util_enable_core_dumps.sh
+  #         archery docker run ${{ matrix.image }}
+  #     - name: Docker Push
+  #       if: >-
+  #         success() &&
+  #         github.event_name == 'push' &&
+  #         github.repository == 'apache/arrow' &&
+  #         github.ref_name == 'main'
+  #       env:
+  #         ARCHERY_DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
+  #         ARCHERY_DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
+  #       continue-on-error: true
+  #       run: archery docker push ${{ matrix.image }}
 
-  build-example:
-    name: C++ Minimal Build Example
-    runs-on: ubuntu-24.04
-    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
-    timeout-minutes: 45
-    steps:
-      - name: Checkout Arrow
-        uses: actions/checkout@v5
-        with:
-          fetch-depth: 0
-          submodules: recursive
-      - name: Check CMake presets
-        run: |
-          cd cpp
-          cmake --list-presets
-      - name: Run minimal example
-        run: |
-          cd cpp/examples/minimal_build
-          docker compose run --rm minimal
+  # build-example:
+  #   name: C++ Minimal Build Example
+  #   runs-on: ubuntu-24.04
+  #   if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
+  #   timeout-minutes: 45
+  #   steps:
+  #     - name: Checkout Arrow
+  #       uses: actions/checkout@v5
+  #       with:
+  #         fetch-depth: 0
+  #         submodules: recursive
+  #     - name: Check CMake presets
+  #       run: |
+  #         cd cpp
+  #         cmake --list-presets
+  #     - name: Run minimal example
+  #       run: |
+  #         cd cpp/examples/minimal_build
+  #         docker compose run --rm minimal
 
-  macos:
-    name: ${{ matrix.architecture }} macOS ${{ matrix.macos-version }} C++
-    runs-on: macos-${{ matrix.macos-version }}
-    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
-    timeout-minutes: 75
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - architecture: AMD64
-            macos-version: "13"
-          - architecture: ARM64
-            macos-version: "14"
-    env:
-      ARROW_AZURE: ON
-      ARROW_BUILD_TESTS: ON
-      ARROW_DATASET: ON
-      ARROW_FLIGHT: ON
-      ARROW_GANDIVA: ON
-      ARROW_GCS: ON
-      ARROW_HDFS: ON
-      ARROW_HOME: /tmp/local
-      ARROW_JEMALLOC: ON
-      ARROW_ORC: ON
-      ARROW_PARQUET: ON
-      ARROW_S3: ON
-      ARROW_SUBSTRAIT: ON
-      ARROW_WITH_BROTLI: ON
-      ARROW_WITH_BZ2: ON
-      ARROW_WITH_LZ4: ON
-      # GH-36013 disabling opentelemetry here because we can't
-      # get the patched version from conda
-      # ARROW_WITH_OPENTELEMETRY: ON
-      ARROW_WITH_SNAPPY: ON
-      ARROW_WITH_ZLIB: ON
-      ARROW_WITH_ZSTD: ON
-    steps:
-      - name: CPU Info
-        run: |
-          sysctl -a | grep cpu
-          sysctl -a | grep "hw.optional"
-      - name: Checkout Arrow
-        uses: actions/checkout@v5
-        with:
-          fetch-depth: 0
-          submodules: recursive
-      - name: Install Dependencies
-        run: |
-          # pkg-config formula is deprecated but it's still installed
-          # in GitHub Actions runner now. We can remove this once
-          # pkg-config formula is removed from GitHub Actions runner.
-          brew uninstall pkg-config || :
-          brew uninstall pkg-config@0.29.2 || :
-          brew bundle --file=cpp/Brewfile
-      - name: Install MinIO
-        run: |
-          $(brew --prefix bash)/bin/bash \
-            ci/scripts/install_minio.sh latest ${ARROW_HOME}
-      - name: Set up Python
-        uses: actions/setup-python@v6.0.0
-        with:
-          python-version: 3.12
-      - name: Install Google Cloud Storage Testbench
-        run: ci/scripts/install_gcs_testbench.sh default
-      - name: Install Azurite Storage Emulator
-        run: ci/scripts/install_azurite.sh
-      - name: Setup ccache
-        run: |
-          ci/scripts/ccache_setup.sh
-      - name: ccache info
-        id: ccache-info
-        run: |
-          echo "cache-dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
-      - name: Cache ccache
-        uses: actions/cache@v4
-        with:
-          path: ${{ steps.ccache-info.outputs.cache-dir }}
-          key: cpp-ccache-macos-${{ matrix.macos-version }}-${{ hashFiles('cpp/**') }}
-          restore-keys: cpp-ccache-macos-${{ matrix.macos-version }}-
-      - name: Build
-        run: |
-          if [ "${{ matrix.macos-version }}" = "13" ]; then
-            # This is a workaround.
-            #
-            # Homebrew uses /usr/local as prefix. So packages
-            # installed by Homebrew also use /usr/local/include. We
-            # want to include headers for packages installed by
-            # Homebrew as system headers to ignore warnings in them.
-            # But "-isystem /usr/local/include" isn't used by CMake
-            # because /usr/local/include is marked as the default
-            # include path. So we disable -Werror to avoid build error
-            # by warnings from packages installed by Homebrew.
-            export BUILD_WARNING_LEVEL=PRODUCTION
-          fi
-          ci/scripts/cpp_build.sh $(pwd) $(pwd)/build
-      - name: Test
-        shell: bash
-        run: |
-          sudo sysctl -w kern.coredump=1
-          sudo sysctl -w kern.corefile=/tmp/core.%N.%P
-          ulimit -c unlimited  # must enable within the same shell
-          ci/scripts/cpp_test.sh $(pwd) $(pwd)/build
+  # macos:
+  #   name: ${{ matrix.architecture }} macOS ${{ matrix.macos-version }} C++
+  #   runs-on: macos-${{ matrix.macos-version }}
+  #   if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
+  #   timeout-minutes: 75
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - architecture: AMD64
+  #           macos-version: "13"
+  #         - architecture: ARM64
+  #           macos-version: "14"
+  #   env:
+  #     ARROW_AZURE: ON
+  #     ARROW_BUILD_TESTS: ON
+  #     ARROW_DATASET: ON
+  #     ARROW_FLIGHT: ON
+  #     ARROW_GANDIVA: ON
+  #     ARROW_GCS: ON
+  #     ARROW_HDFS: ON
+  #     ARROW_HOME: /tmp/local
+  #     ARROW_JEMALLOC: ON
+  #     ARROW_ORC: ON
+  #     ARROW_PARQUET: ON
+  #     ARROW_S3: ON
+  #     ARROW_SUBSTRAIT: ON
+  #     ARROW_WITH_BROTLI: ON
+  #     ARROW_WITH_BZ2: ON
+  #     ARROW_WITH_LZ4: ON
+  #     # GH-36013 disabling opentelemetry here because we can't
+  #     # get the patched version from conda
+  #     # ARROW_WITH_OPENTELEMETRY: ON
+  #     ARROW_WITH_SNAPPY: ON
+  #     ARROW_WITH_ZLIB: ON
+  #     ARROW_WITH_ZSTD: ON
+  #   steps:
+  #     - name: CPU Info
+  #       run: |
+  #         sysctl -a | grep cpu
+  #         sysctl -a | grep "hw.optional"
+  #     - name: Checkout Arrow
+  #       uses: actions/checkout@v5
+  #       with:
+  #         fetch-depth: 0
+  #         submodules: recursive
+  #     - name: Install Dependencies
+  #       run: |
+  #         # pkg-config formula is deprecated but it's still installed
+  #         # in GitHub Actions runner now. We can remove this once
+  #         # pkg-config formula is removed from GitHub Actions runner.
+  #         brew uninstall pkg-config || :
+  #         brew uninstall pkg-config@0.29.2 || :
+  #         brew bundle --file=cpp/Brewfile
+  #     - name: Install MinIO
+  #       run: |
+  #         $(brew --prefix bash)/bin/bash \
+  #           ci/scripts/install_minio.sh latest ${ARROW_HOME}
+  #     - name: Set up Python
+  #       uses: actions/setup-python@v6.0.0
+  #       with:
+  #         python-version: 3.12
+  #     - name: Install Google Cloud Storage Testbench
+  #       run: ci/scripts/install_gcs_testbench.sh default
+  #     - name: Install Azurite Storage Emulator
+  #       run: ci/scripts/install_azurite.sh
+  #     - name: Setup ccache
+  #       run: |
+  #         ci/scripts/ccache_setup.sh
+  #     - name: ccache info
+  #       id: ccache-info
+  #       run: |
+  #         echo "cache-dir=$(ccache --get-config cache_dir)" >> $GITHUB_OUTPUT
+  #     - name: Cache ccache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ${{ steps.ccache-info.outputs.cache-dir }}
+  #         key: cpp-ccache-macos-${{ matrix.macos-version }}-${{ hashFiles('cpp/**') }}
+  #         restore-keys: cpp-ccache-macos-${{ matrix.macos-version }}-
+  #     - name: Build
+  #       run: |
+  #         if [ "${{ matrix.macos-version }}" = "13" ]; then
+  #           # This is a workaround.
+  #           #
+  #           # Homebrew uses /usr/local as prefix. So packages
+  #           # installed by Homebrew also use /usr/local/include. We
+  #           # want to include headers for packages installed by
+  #           # Homebrew as system headers to ignore warnings in them.
+  #           # But "-isystem /usr/local/include" isn't used by CMake
+  #           # because /usr/local/include is marked as the default
+  #           # include path. So we disable -Werror to avoid build error
+  #           # by warnings from packages installed by Homebrew.
+  #           export BUILD_WARNING_LEVEL=PRODUCTION
+  #         fi
+  #         ci/scripts/cpp_build.sh $(pwd) $(pwd)/build
+  #     - name: Test
+  #       shell: bash
+  #       run: |
+  #         sudo sysctl -w kern.coredump=1
+  #         sudo sysctl -w kern.corefile=/tmp/core.%N.%P
+  #         ulimit -c unlimited  # must enable within the same shell
+  #         ci/scripts/cpp_test.sh $(pwd) $(pwd)/build
 
-  windows:
-    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
-    name: AMD64 Windows 2022 AVX2 C++
-    uses: ./.github/workflows/cpp_windows.yml
-    with:
-      arch: x64
-      os: windows-2022
-      simd-level: AVX2
+  # windows:
+  #   if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
+  #   name: AMD64 Windows 2022 AVX2 C++
+  #   uses: ./.github/workflows/cpp_windows.yml
+  #   with:
+  #     arch: x64
+  #     os: windows-2022
+  #     simd-level: AVX2
 
   windows-mingw:
     name: AMD64 Windows MinGW ${{ matrix.msystem_upper }} C++
@@ -311,6 +311,7 @@ jobs:
       ARROW_FLIGHT: ON
       ARROW_FLIGHT_SQL: ON
       ARROW_FLIGHT_SQL_ODBC: ON
+      ARROW_ODBC_LOG_LEVEL: debug
       ARROW_GANDIVA: ON
       ARROW_GCS: ON
       ARROW_HDFS: OFF
